image:
  repository: sensrnetnl/multichain-node
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

settings:
  connectToExistingChain: false # If false, create a new network
  mainNodeHost: 1.2.3.4 # is ignored if connectToExistingChain is false
  chainName: SensRNet
  p2pPort: 8571
  rpc:
    port: 8570
    username: username
    password: password

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}
  ## PV Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If undefined (the default) or set to null, no storageClassName spec is
  ## set, choosing the default provisioner
  # storageClass: null

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  annotations: {}
  ## Serive Traffic Policy
  ## By setting externalTrafficPolicy to Local, Multichain will communicate its
  ## external IP to other nodes instead of
  ## its internal IP address
  ## Can only be set if type: LoadBalancer is used
  # externalTrafficPolicy: Local

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  routes:
    - match: HostSNI(`*`)
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}