replicaCount: 1

image:
  repository: sensrnetnl/multichain-node
  pullPolicy: IfNotPresent

settings:
  connectToExistingChain: false # If false, create a new network
  mainNodeHost: 1.2.3.4 # is ignored if connectToExistingChain is false
  chainName: SensRNet
  p2pPort: 8571
  rpc:
    port: 8570
    username: username
    password: password

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}