image:
  # -- SensRNet multichain-node image name
  repository: sensrnetnl/multichain-node
  # -- SensRNet multichain-node image pull policy
  pullPolicy: IfNotPresent
  # -- SensRNet multichain-node image tag
  tag: ""

# -- String to partially override multichain-node.fullname
nameOverride: ""
# -- String to fully override multichain-node.fullname
fullnameOverride: ""

settings:
  # -- Whether to connect to an existing chain, or create a new one
  connectToExistingChain: false
  # -- Hostname or IP address of the multichain node this node needs to be connected to. Is ignored if connectToExistingChain is false
  mainNodeHost: ""
  # -- Name of the chain to create or connect to
  chainName: SensRNet
  # -- Private key of this node to join the chain with
  privateKey: ""
  # -- Port used for external access
  p2pPort: 8571
  rpc:
    # -- Port used for internal (Kubernetes Cluster) JSON-RPC API
    port: 8570
    # -- JSON-RPC API username
    username: username
    # -- JSON-RPC API password
    password: password

persistence:
  # -- Enable multichain persistence using PVC
  enabled: true
  # -- PVC Access Mode for multichain-node data volume
  accessModes:
    - ReadWriteOnce
  # -- PVC Storage Request for multichain-node data volume
  size: 1Gi
  # -- Additional PVC annotations
  annotations: {}
  ## PV Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If undefined (the default) or set to null, no storageClassName spec is
  ## set, choosing the default provisioner
  # storageClass: null

# -- SensRNet multichain-node pods' Security Context
podSecurityContext: {}
# -- SensRNet multichain-node containers' Security Context
securityContext: {}

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- Service annotations (evaluated as a template)
  annotations: {}
  ## Service Traffic Policy
  ## By setting externalTrafficPolicy to Local, Multichain will communicate its
  ## external IP to other nodes instead of
  ## its internal IP address
  ## Can only be set if type: LoadBalancer is used
  # externalTrafficPolicy: Local

ingress:
  # -- Enable ingress controller resource
  enabled: false
  # -- Ingress annotations (evaluated as a template)
  # @default -- Check `values.yaml` file
  annotations:
    kubernetes.io/ingress.class: traefik
  # -- Ingress routes (evaluated as a template)
  # @default -- Check `values.yaml` file
  routes:
    - match: HostSNI(`*`)

# -- The requested resources and resources limits for the Multichain-node container (evaluated as a template)
resources: {}
# -- Node labels for pod assignment (evaluated as a template)
nodeSelector: {}
# -- Tolerations for pod assignment (evaluated as a template)
tolerations: []
# -- Affinity for pod assignment (evaluated as a template)
affinity: {}
