replicaCount: 1

image:
  repository: sensrnetnl/registry-frontend
  pullPolicy: IfNotPresent
  tag: ""

settings:
  apiUrl: /api
  oidc_issuer: ""
  oidc_client_id: registry-frontend

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  routes:
    - match: PathPrefix(`/`)
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
