apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry-backend.fullname" . }}
  labels:
    {{- include "registry-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry-backend.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: EVENT_STORE_HOST
            value: {{ .Values.settings.eventstore.host }}
          - name: EVENT_STORE_PORT
            value: "{{ .Values.settings.eventstore.port }}"
          - name: JWT_SECRET
            value: your-face
          - name: JWT_ACCESS_EXPIRES_IN
            value: "86400"
          - name: JWT_REFRESH_EXPIRES_IN
            value: "604800"
          - name: MONGO_HOST
            value: {{ .Values.settings.mongo.host }}
          - name: MONGO_PORT
            value: "{{ .Values.settings.mongo.port }}"
          - name: MONGO_DATABASE
            value: {{ .Values.settings.mongo.database }}
          ports:
          - name: http
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: check-mongo-ready
          image: mongo:4.4.3
          command: ['sh', '-c',
            'until mongo --host {{ .Values.settings.mongo.host }}:27017 --eval "printjson(db.serverStatus())";
            do echo waiting for mongo; sleep 10; done;']
