replicaCount: 1

image:
  repository: sensrnetnl/central-viewer
  pullPolicy: IfNotPresent
  tag: ""

settings:
  geoserverUrl: /geoserver/sensrnet/ows

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  routes:
    - match: PathPrefix(`/`)
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
