apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "central-viewer-geoserver.fullname" . }}
  labels:
    {{- include "central-viewer-geoserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "central-viewer-geoserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "central-viewer-geoserver.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: docker_app_name
              value: geoserver
            - name: INITIAL_MEMORY
              value: {{ .Values.settings.initialMemory }}
            - name: MAXIMUM_MEMORY
              value: {{ .Values.settings.maximumMemory }}
            - name: geoserver_adminpw
              value: {{ .Values.settings.adminPw }}
            - name: geoserver_console_disabled
              value: {{ .Values.settings.webInterfaceDisabled }}
            - name: MONGO_HOST
              value: {{ .Values.settings.mongo.host }}
            - name: MONGO_PORT
              value: {{ .Values.settings.mongo.port | quote }}
            - name: MONGO_DATABASE
              value: {{ .Values.settings.mongo.database }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
