# Default values for registry-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

traefik: # configuration from https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  enabled: true
  deployment:
    kind: DaemonSet
  ports:
    multichain:
      port: 8571
      expose: true
      exposedPort: 8571
      protocol: TCP
  additionalArguments:
    - --accesslog=true
    - --accesslog.format=json
    - --accesslog.fields.names.RequestHost=keep
    - --accesslog.fields.headers.names.X-Forwarded-By=keep
    - --accesslog.fields.headers.names.X-Forwarded-Host=keep
    - --accesslog.fields.headers.names.X-Forwarded-Proto=keep
    - --accesslog.fields.headers.names.X-Forwarded-For=keep
    - --api
    - --api.insecure=true
    - --entrypoints.web.address=:8000
    - --entrypoints.web.forwardedHeaders.insecure=true
    - --entrypoints.websecure.address=:8443
    - --entrypoints.multichain.address=:8571
    - --metrics.prometheus
  ingressRoute:
    dashboard:
      enabled: true

multichain-node:
  enabled: true
  multiChainNode:
    connectToExistingChain: true # If false, create a new network
    # mainNodeHost: 20.73.205.7 # is ignored if connectToExistingChain is false
    mainNodeHost: 20.73.148.161
    chainName: SensRNet
    rpc:
      username: username
      password: password

registry-backend:
  enabled: true
  registryBackend:
    eventstore:
      host: registry-node-eventstore
      port: ext-tcp-port
    mongo:
      host: registry-node-mongodb-headless
      port: 27017
      database: sensrnet

mongodb: # configuration from https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
  enabled: true
  imageTag: 4.4.3
  architecture: replicaset
  auth:
    enabled: false
  replicaCount: 1
  persistence:
    enabled: false
    accessModes:
      - ReadWriteOnce
    size: 50Gi
  service:
    type: ClusterIP
    port: 27017
    portName: mongo-service
  podAntiAffinityPreset: hard

eventstore: # configuration from https://github.com/EventStore/EventStore.Charts/blob/master/stable/eventstore/values.yaml
  enabled: true
  clusterSize: 1
  imageTag: release-5.0.1
  eventStoreConfig:
    EVENTSTORE_DISCOVER_VIA_DNS: true
    EVENTSTORE_CLUSTER_DNS: registry-node-eventstore
    EVENTSTORE_DEV: true
    EVENTSTORE_MEM_DB: false
    EVENTSTORE_RUN_PROJECTIONS: All
    EVENTSTORE_START_STANDARD_PROJECTIONS: true
    EVENTSTORE_ENABLE_EXTERNAL_TCP: true
    EVENTSTORE_DISABLE_EXTERNAL_TCP_TLS: true
  scavenging:
    enabled: true
  persistence:
    enabled: false
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - eventstore
        topologyKey: "kubernetes.io/hostname"

sync-bridge:
  enabled: true
  syncBridge:
    eventstore:
      host: registry-node-eventstore
      port: ext-tcp-port
    multichain:
      host: registry-node-multichain-node
      port: 8570
      rpc:
        username: username
        password: password
    mongo:
      host: registry-node-mongodb-headless
      port: 27017
      database: sensrnet

registry-frontend:
  enabled: true
  replicaCount: 1
