replicaCount: 1

image:
  repository: sensrnetnl/central-viewer-geoserver
  pullPolicy: IfNotPresent
  tag: ""

settings:
  initialMemory: 2G
  maximumMemory: 4G
  adminPw: changeit
  mongo:
    host: registry-backend-mongodb-headless
    port: 27017
    database: sensrnet

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  routes:
    - match: PathPrefix(`/geoserver`)
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
