{{- if .Values.ingress.enabled -}}
{{- $fullName := include "multichain-node.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "multichain-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - multichain
  routes:
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ .Values.settings.p2pPort }}
{{- end }}