{{- if .Values.ingress.enabled -}}
{{- $fullName := include "multichain-node.fullname" . -}}
{{- $svcPort := .Values.settings.p2pPort -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "multichain-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - multichain
  routes:
    {{- range .Values.ingress.routes }}
    - kind: Rule
      match: {{ .match | quote }}
      services:
      - name: {{ $fullName }}
        port: {{ $svcPort }}
    {{- end }}
{{- end }}
