apiVersion: v1
kind: Service
metadata:
  name: {{ include "multichain-node.fullname" . }}
  labels:
    {{- include "multichain-node.labels" . | nindent 4 }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.settings.rpc.port }}
      targetPort: rpc
    - name: tcp
      port: {{ .Values.settings.networkPort }}
      targetPort: tcp
    - name: web
      port: 2750
      targetPort: web
  selector:
    {{- include "multichain-node.selectorLabels" . | nindent 4 }}
