apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry-frontend.fullname" . }}
  labels:
    {{- include "registry-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry-frontend.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_URL
              value: {{ .Values.settings.apiUrl }}
            - name: OIDC_ISSUER
              value: {{ .Values.settings.oidc_issuer }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.settings.oidc_client_id }}
          args:
            - -health-status=true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: http
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
