replicaCount: 0

image:
  repository: sensrnetnl/registry-backend
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""


settings:
  requireAuthentication: true
  oidc_issuer: ""
  oidc_jwks_url: ""
  oidc_audience: registry-frontend
  eventstore:
    host: registry-backend-eventstore # NAME-eventstore, NAME has to match Helm deployment name
    port: ext-tcp-port
  mongo:
    host: registry-backend-mongodb-headless # NAME-mongodb-headless, NAME has to match Helm deployment name
    port: 27017
    database: sensrnet

mongodb: # configuration from https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
  enabled: true
  imageTag: 4.4.3
  architecture: replicaset
  auth:
    enabled: false
  replicaCount: 3
  persistence:
    enabled: true
    size: 10Gi
  service:
    type: ClusterIP
    port: 27017
    portName: mongo-service
  resources:
    limits:
     cpu: 500m
     memory: 556Mi
    requests:
     cpu: 100m
     memory: 254Mi
  podAntiAffinityPreset: hard

eventstore: # configuration from https://github.com/EventStore/EventStore.Charts/blob/master/stable/eventstore/values.yaml
  enabled: true
  clusterSize: 3
  imageTag: release-5.0.9
  eventStoreConfig:
    EVENTSTORE_DISCOVER_VIA_DNS: true
    EVENTSTORE_CLUSTER_DNS: registry-backend-eventstore
    EVENTSTORE_RUN_PROJECTIONS: All
    EVENTSTORE_START_STANDARD_PROJECTIONS: true
    EVENTSTORE_ENABLE_EXTERNAL_TCP: true
    EVENTSTORE_DISABLE_EXTERNAL_TCP_TLS: true
  scavenging:
    enabled: true
  persistence:
    enabled: true
    size: 12Gi
  resources:
    limits:
     cpu: 700m
     memory: 1.5Gi
    requests:
     cpu: 400m
     memory: 528Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - eventstore
          - key: app.kubernetes.io/component
            operator: In
            values:
            - database
        topologyKey: "kubernetes.io/hostname"

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: sensrnet.local
  path: /api
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
